services:
  - type: web
    name: whatsapp-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python whatsapp_webhook.py"
    envVars:
      - key: FLASK_ENV
        value: production
